wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695477102.133401
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 64
      - 103
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 64
      - 103
      3:
      - 1
      - 13
      - 23
      4: 3.8.17
      5: 0.15.10
      6: 4.33.2
      8:
      - 4
      - 5
